# Generated by Django 3.1.1 on 2020-10-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
