# Generated by Django 3.1.1 on 2020-10-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20201019_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
