# Generated by Django 3.1.1 on 2020-10-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_completeorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeorder',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
